name: "CI"
on:
  # Run only when pushing to master branch, and making PRs
  push:
    branches:
      - '*'
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64-linux
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: srid
      - name: Build  ${{ matrix.arch }} 🔨
        run: nix run github:srid/nixci
