name: "CI"
on:
  # Run only when pushing to master branch, and making PRs
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Build 🔨
        id: build
        run: |
          nix build -j auto -L
      - name: Flake checks 🧪
        run: |
          # Sandbox must be disabed for:
          # https://github.com/srid/haskell-flake/issues/21
          nix \
            --option sandbox false \
            flake check -L \
            --override-input systems github:nix-systems/x86_64-linux
